openapi: 3.0.0
info:
  title: ODX API
  version: 1.0.0
  description: API para gerenciamento de casos e evidências na Odontologia Legal
servers:
  - url: https://odx-pericias-back.onrender.com

paths:

  # ROTAS DE AUTENTICAÇÃO
  /auth/register:
    post:
      summary: Registra um novo usuário
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Usuário criado com sucesso

  /auth/login:
    post:
      summary: Autentica um usuário
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login bem-sucedido

  /auth/logout:
    post:
      summary: Realiza logout do usuário
      tags: [Auth]
      responses:
        '200':
          description: Logout efetuado

  /auth/listusers:
    get:
      summary: Lista todos os usuários
      tags: [Auth]
      responses:
        '200':
          description: Lista de usuários

  # ROTAS DE CASOS
  /cases:
    post:
      summary: Cadastra um novo caso
      tags: [Cases]
      responses:
        '201':
          description: Caso cadastrado com sucesso

    get:
      summary: Lista todos os casos
      tags: [Cases]
      responses:
        '200':
          description: Lista de casos

  /cases/{caseId}/status:
    patch:
      summary: Atualiza o status de um caso
      tags: [Cases]
      parameters:
        - in: path
          name: caseId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status atualizado com sucesso

  # ROTAS DE EVIDÊNCIAS
  /evidence/text:
    post:
      summary: Upload de evidência textual
      tags: [Evidências]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Evidence'
      responses:
        '201':
          description: Texto enviado

  /evidence/image:
    post:
      summary: Upload de imagem como evidência
      tags: [Evidências]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Imagem enviada

  /evidence/{caseId}:
    post:
      summary: Adiciona evidência a um caso
      tags: [Evidências]
      parameters:
        - in: path
          name: caseId
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Evidência adicionada

  /evidence/coletar:
    post:
      summary: Coleta evidências
      tags: [Evidências]
      responses:
        '200':
          description: Evidências coletadas

  /evidence/analisar:
    post:
      summary: Analisa evidências
      tags: [Evidências]
      responses:
        '200':
          description: Evidências analisadas

  /evidence/enviar:
    get:
      summary: Envia dados complementares ao caso
      tags: [Evidências]
      responses:
        '200':
          description: Dados enviados com sucesso

  /evidence/gerar-laudo/{caseId}:
    post:
      summary: Gera um laudo a partir das evidências
      tags: [Evidências]
      parameters:
        - in: path
          name: caseId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Laudo gerado

  # ROTAS DE RELATÓRIOS (LAUDOS)
  /report:
    post:
      summary: Cria um novo laudo
      tags: [Laudos]
      responses:
        '201':
          description: Laudo criado

    get:
      summary: Lista todos os laudos
      tags: [Laudos]
      responses:
        '200':
          description: Lista de laudos

  /report/generate/{caseId}:
    post:
      summary: Gera o conteúdo de um laudo
      tags: [Laudos]
      parameters:
        - in: path
          name: caseId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Conteúdo gerado

  /report/sign/{reportId}:
    post:
      summary: Assina digitalmente o laudo
      tags: [Laudos]
      parameters:
        - in: path
          name: reportId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Laudo assinado

  /report/pdf/{reportId}:
    get:
      summary: Exporta laudo em PDF
      tags: [Laudos]
      parameters:
        - in: path
          name: reportId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: PDF gerado com sucesso

  /report/{reportId}:
    get:
      summary: Busca laudo por ID
      tags: [Laudos]
      parameters:
        - in: path
          name: reportId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes do laudo

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
        senha:
          type: string
        role:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        senha:
          type: string
    User:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
        senha:
          type: string
        perfil:
          type: string
          enum:
            - Admin
            - Perito
            - Assistente
        rg:
          type: string
        cro:
          type: string
    Case:
      type: object
      properties:
        titulo:
          type: string
        descricao:
          type: string
        status:
          type: string
          enum:
            - Em andamento
            - Finalizado
            - Arquivado
        responsavel:
          type: string
        evidencias:
          type: array
          items:
            type: string
        dataCriacao:
          type: string
          format: date-time
    Evidence:
      type: object
      properties:
        tipo:
          type: string
        dataColeta:
          type: string
          format: date-time
        coletadoPor:
          type: string
        url:
          type: string
        categoria:
          type: string
          enum:
            - Radiografia Panorâmica
            - Imagem Intraoral
            - Radiografia Periapical
            - Análise de Prontuário
            - Outro
    Report:
      type: object
      properties:
        titulo:
          type: string
        conteudo:
          type: string
        peritoResponsavel:
          type: string
        casoRelacionado:
          type: string
        dataCriacao:
          type: string
          format: date-time