openapi: 3.0.0
info:
  title: ODX API
  version: 1.0.0
  description: API para gerenciamento de casos e evidências na Odontologia Legal

servers:
  - url: https://odx-pericias-back.onrender.com

paths:

  # ROTAS DE AUTENTICAÇÃO
  /api/auth/register:
    post:
      summary: Registra um novo usuário
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuário criado com sucesso

  /api/auth/login:
    post:
      summary: Autentica um usuário
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login bem-sucedido

  /api/auth/logout:
    post:
      summary: Realiza logout do usuário
      tags: [Auth]
      responses:
        '200':
          description: Logout efetuado

  /api/auth/listusers:
    get:
      summary: Lista todos os usuários
      tags: [Auth]
      responses:
        '200':
          description: Lista de usuários

  # ROTAS DE CASOS
  /api/casos:
    post:
      summary: Criar um novo caso
      description: Cria um novo caso com as informações fornecidas.
      tags: [Casos]
      security:
        - BearerAuth: []
      requestBody:
        description: Dados do novo caso a ser criado
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  example: "Caso de identificação de vítima"
                descricao:
                  type: string
                  example: "Caso envolvendo a identificação de uma vítima de acidente."
                responsavel:
                  type: string
                  example: "60c72b2f9fd1a2b9b2a557a6"
                dataCriacao:
                  type: string
                  format: date
                  example: "2025-04-12"
      responses:
        '201':
          description: Caso criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "Caso cadastrado com sucesso!"
                  caso:
                    $ref: '#/components/schemas/Case'
        '400':
          description: Erro na solicitação

  /api/casos/{caseId}/status:
    patch:
      summary: Atualizar status do caso
      description: Atualiza o status de um caso existente.
      tags: [Casos]
      parameters:
        - in: path
          name: caseId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [Em andamento, Finalizado, Arquivado]
                  example: "Finalizado"
      responses:
        '200':
          description: Status do caso atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
        '400':
          description: Erro na solicitação
        '404':
          description: Caso não encontrado

  /api/casos/{caseId}/finalizar:
    patch:
      summary: Finalizar caso
      description: Finaliza um caso específico e altera o status para "Finalizado".
      tags: [Casos]
      parameters:
        - in: path
          name: caseId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Caso finalizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "Caso 'Caso de identificação de vítima' finalizado com sucesso."
        '404':
          description: Caso não encontrado
        '500':
          description: Erro ao finalizar caso

  # ROTAS DE EVIDÊNCIAS
  /api/evidence:
    post:
      summary: Adiciona uma nova evidência (imagem ou texto)
      tags: [Evidências]
      parameters:
        - name: caseId
          in: path
          required: true
          schema:
            type: string
        - name: tipo
          in: query
          required: true
          schema:
            type: string
            enum: [imagem, texto]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [categoria, vitima, sexo, estadoCorpo, coletadoPor]
              properties:
                categoria:
                  type: string
                vitima:
                  type: string
                  enum: [identificada, não identificada]
                sexo:
                  type: string
                  enum: [masculino, feminino, indeterminado]
                estadoCorpo:
                  type: string
                  enum: [inteiro, fragmentado, carbonizado, putrefacto, esqueleto]
                lesoes:
                  type: string
                coletadoPor:
                  type: string
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: image/*
          application/json:
            schema:
              type: object
              required: [categoria, vitima, sexo, estadoCorpo, coletadoPor, conteudo]
              properties:
                categoria:
                  type: string
                vitima:
                  type: string
                  enum: [identificada, não identificada]
                sexo:
                  type: string
                  enum: [masculino, feminino, indeterminado]
                estadoCorpo:
                  type: string
                  enum: [inteiro, fragmentado, carbonizado, putrefacto, esqueleto]
                lesoes:
                  type: string
                coletadoPor:
                  type: string
                conteudo:
                  type: string
                  example: "Descrição detalhada da evidência textual"
      responses:
        '200':
          description: Evidência adicionada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "Evidência adicionada com sucesso."
                  evidence:
                    $ref: '#/components/schemas/Evidence'
        '400':
          description: Requisição inválida ou dados ausentes
        '401':
          description: Não autorizado
        '500':
          description: Erro interno do servidor
      security:
        - bearerAuth: []

  # ROTAS DE RELATÓRIOS
  /api/report:
    get:
      summary: Gera um relatório pericial para um caso
      parameters:
        - in: path
          name: caseId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Relatório gerado com sucesso
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Caso ou relatório não encontrado
        '500':
          description: Erro ao gerar o relatório

  /api/report/sign/{reportId}:
    patch:
      summary: Assina digitalmente um relatório
      parameters:
        - in: path
          name: reportId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Relatório assinado digitalmente com sucesso
        '404':
          description: Relatório não encontrado
        '500':
          description: Erro ao assinar o relatório

components:
  schemas:
    Case:
      type: object
      properties:
        _id:
          type: string
        titulo:
          type: string
          example: "Caso de identificação de vítima"
        descricao:
          type: string
          example: "Caso envolvendo a identificação de uma vítima de acidente."
        status:
          type: string
          enum: [Em andamento, Finalizado, Arquivado]
        responsavel:
          type: string
        evidencias:
          type: array
          items:
            type: string
        dataCriacao:
          type: string
          format: date

    Evidence:
      type: object
      properties:
        _id:
          type: string
        tipo:
          type: string
          enum: [imagem, texto]
        categoria:
          type: string
        dataUpload:
          type: string
          format: date-time
        vitima:
          type: string
          enum: [identificada, não identificada]
        sexo:
          type: string
          enum: [masculino, feminino, indeterminado]
        estadoCorpo:
          type: string
          enum: [inteiro, fragmentado, carbonizado, putrefacto, esqueleto]
        lesoes:
          type: string
        conteudo:
          type: string
        imagemURL:
          type: string
          format: uri
        caso:
          type: string
        coletadoPor:
          type: string
        laudo:
          type: string

    Report:
      type: object
      properties:
        _id:
          type: string
        titulo:
          type: string
        descricao:
          type: string
        objetoPericia:
          type: string
        analiseTecnica:
          type: string
        metodoUtilizado:
          type: string
        destinatario:
          type: string
        materiaisUtilizados:
          type: string
        examesRealizados:
          type: string
        consideracoesTecnicoPericiais:
          type: string
        conclusaoTecnica:
          type: string
        caso:
          type: string
        evidencias:
          type: array
          items:
            type: string
        criadoEm:
          type: string
          format: date-time
        assinadoDigitalmente:
          type: boolean

    User:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
          format: email
        senha:
          type: string
        perfil:
          type: string
          enum: [Admin, Perito, Assistente]
        rg:
          type: string
        cro:
          type: string

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        senha:
          type: string